### ISSUE TITLE
Collateral Ratio Calculation

### ISSUE THREAD

**Issue by codynhat** [tellor-io/chorus#28]
I am having trouble understanding how the `collateralRatio` is being calculated. I'm not sure if there is a mistake in the calculation or a mistake in my understanding.

I have an anthem deployed with:
- 10 notes outstanding
- Balance of 100 collateral tokens
- Note price of $1
- Collateral price of $2

This means the total value of collateral is ($2 x 100) = $200 and the value of outstanding notes is (10 x $1) = $10. I would expect `collateralRatio` in this scenario to be $200/$10 which is `20` or `2000%`. Instead, it is `1.05` or `105%`. 

Am I misunderstanding what `collateralRatio` is or is there a bug?

**Comment by themandalore** [comment]
yup, it looks like the last line should be: return wdiv(_collateralValue/_tokenValue); 

I'll fix it and push it today.... @krasi-georgiev  thoughts?

**Comment by themandalore** [comment]
fixed in the next PR.  Just an issue about what the definition of collateralRatio was, but this way is clearer

**Comment by codynhat** [comment]
Sounds good!
