### ISSUE TITLE
Add tax on witdraw or a delay a day/3hours? 

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/chorus#3]
To avoid gaming on the collateral price.

**Comment by themandalore** [comment]
Should it be a variable (the delay and the tax), or how does a default 1 day, 1% sound?

**Comment by krasi-georgiev** [comment]
I can't remember about this one, didn't we discuss it decided against it.

**Comment by themandalore** [comment]
I think we did, but then I was thinking about it again looking at the code and wondering why it wasn't in there.  I really think we're just asking for arbitrage with a set up like this.  I think a small penalty and a delay will keep the arbitrageurs out of the system nicely
